//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APPGIROS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GGIROS
    {
        public int Id_Giros { get; set; }
        public string Nombre { get; set; }
        public int Id_Ciudad { get; set; }
    
        public virtual CIUDAD CIUDAD { get; set; }
    }
}
